name: Push docker image

on:
  push:
    tags: 'v*'
  workflow_dispatch:

env:
  IMAGE_NAME: minecraftspeedproxy

jobs:
  push-ghcr:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v2
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CI_PACKAGE }}
      - name: Build && Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/allesugo/${{ env.IMAGE_NAME }}:latest