name: Build and release

on:
  push:
    tags: 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up xmake
        run: sudo add-apt-repository ppa:xmake-io/xmake && sudo apt update && sudo apt install xmake
      
      - name: Install deps
        run: sudo apt update && sudo apt upgrade -y && sudo apt-get install manpages-posix-dev glibc-doc manpages-posix build-essential git -y

      - name: Get version
        run: git fetch --tags && version=$(git describe --tags) && version1=${version#v} && export VERSION=${version1%%-*}

      - name: Build
        run: xmake build -y && cp build/linux/x86_64/release/minecraftspeedproxy .

      - name: Pack deb
        run: bash <(curl -fsSL https://fastly.jsdelivr.net/gh/AllesUgo/Minecraft-Speed-Proxy@master/scripts/release.sh)
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Minecraft-Speed-Proxy-linux-amd64.deb
            minecraftspeedproxy
