name: Build and release

on:
  push:
    tags: 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up xmake
        run: bash <(curl -fsSL https://xmake.io/shget.text)
      
      - name: Install deps
        run: sudo apt-get install manpages-posix-dev glibc-doc manpages-posix build-essential -y

      - name: Build
        run: xmake build -y && cp build/linux/x86_64/release/minecraftspeedproxy .

      - name: Pack deb
        run: bash <(curl -fsSL https://gist.githubusercontent.com/SkyTeamWater/178233a8d71155927ab2540fd8cc3db6/raw/3a32e593b476de09e2390609e53aedefd0a85605/release.sh)
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Minecraft-Speed-Proxy-linux-amd64.deb
            minecraftspeedproxy
