name: C/C++ CI

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]

jobs:
  ubuntu-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: mkdir build-ubuntu && cd build-ubuntu && cmake  ..
      - name: build
        run: cmake --build build-ubuntu

  win-build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: mkdir build-windows && cd build-windows && cmake ..
      - name: build
        run: cmake --build build-windows
