name: Test commit and pr

on:
  pull_request:
  push:

jobs:

  build-with-gcc:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-18.04, ubuntu-16.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Build with Makefile
        run: export VERSION=[ci]$(git rev-parse HEAD) && make -e CXX=gcc && ./minecraftspeedproxy --version

  build-with-clang:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-18.04, ubuntu-16.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Build with Makefile
        run: export VERSION=[ci]$(git rev-parse HEAD) && make -e CXX=clang && ./minecraftspeedproxy --version
